In [1]:
import numpy as np

函数原型:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

In [3]:
# 创建向量:
v = [1,2,3,4,5]
print(np.array(v))


[1 2 3 4 5]


In [8]:
# 创建矩阵
print(np.array([v,v]))

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [10]:
# 创建矩阵
print(np.array( [[1,1,1,1,1],v] ) )

[[1 1 1 1 1]
 [1 2 3 4 5]]


In [13]:
# ndmin 
print('dmin = 1 : ', np.array(v, ndmin=1))
print('dmin = 2 : ', np.array(v, ndmin=2))
print('dmin = 3 : ', np.array(v, ndmin=3))

dmin = 1 :  [1 2 3 4 5]
dmin = 2 :  [[1 2 3 4 5]]
dmin = 3 :  [[[1 2 3 4 5]]]


In [15]:
# dtype 
print(np.array(v, dtype=np.float))
print(np.array(v, dtype=np.int16))
print(np.array(v, dtype=np.complex))  # 复数类型

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
