## np.ndarray的属性<br>
![ndarray的属性](img/2_ndarray_attr_.png)

In [2]:
import numpy as np

In [9]:
# ndim 表示数组的维度数
a = np.arange(24)
print('a = ', a)
print('a.ndim = ', a.ndim)
b = a.reshape((2,3,4))  # b现在有三个维度, 有两层, 每层是一个3x4的矩阵
print('b = ', b)
print('b.ndim = ', b.ndim)

a =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
a.ndim =  1
b =  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b.ndim =  3


In [12]:
# shape 属性是一个元组, 元组的第一个数表示第一维的大小, 第二个数表示第二维的大小,依次类推
print(b.shape)
b.shape = (4, 6) # 可以通过给shape属性赋值, 来修改一个ndarray的形状
print(b)

(4, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
